### ISSUE TITLE
split bug in fujitou_angry

### ISSUE THREAD

**Issue by ybenjo** [voice-statistics/voice-statistics.github.com#2]
by @shirayu

**Comment by ybenjo** [comment]
043, 046, 055, 056

**Comment by shirayu** [comment]
「ファイル先頭から有音区間までのフレーム数」と
「有音区間が終わってからファイル末尾までのフレーム数」
を出力するコードを書きました．
よければお使いください．

https://gist.github.com/shirayu/2bbddf4704b5f48193fb18bdcdd5dfe1

**Comment by ybenjo** [comment]
@shirayu わざわざありがとうございます．確認修正含め週末に対応致します．

**Comment by ybenjo** [comment]
いただいたスクリプトで確認し修正を反映しました．本当にありがとうございました．他のファイルも同スクリプトでチェックします．
