### ISSUE TITLE
一部データがダウンロード不可能

### ISSUE THREAD

**Issue by tarepan** [voice-statistics/voice-statistics.github.com#5]
# 概要
"上村彩子 - 通常" のみダウンロード不可能な状態にあります。  
ほかの8セットは正常にダウンロード可能です。  

# 状況
"上村彩子 - 通常" をダウンロードしようとしたところ、サーバーからの応答がなく、後にエラーを返してきます。  
数週間前にダウンロードして利用させていただいていた際には、正常にダウンロードされました。  
ここ数日で何回かトライしているため、temporarilyな問題ではないと推測されます。  
ほかの8データセットは正常にダウンロード可能です。  

# エラーコード
in browser,  
```
Error 503 first byte timeout
first byte timeout

Guru Mediation:
Details: cache-nrt6148-NRT 1541740866 3591099822

Varnish cache server
```

**Comment by ybenjo** [comment]
@tarepan 
反応が遅れてしまい申し訳ありません．こちらでも確認しました．
google drive にミラーファイルを配置し，トップページからもリンクを張りました．
こちらからダウンロードできるか試してもらえないでしょうか．
https://drive.google.com/uc?id=1nNnemZV88JT-ZuVY4sxCsvj86YugxPu2&export=download

**Comment by tarepan** [comment]
ミラーサイトからのダウンロード, 音声ファイルの再生に成功しました。  
対応ありがとうございました。  

素晴らしいコーパスをありがとうございます、声質変換実験にとても重宝しています。

**Comment by ybenjo** [comment]
@tarepan 
ご活用いただきありがとうございます．また何かあったらお願いします．
