### ISSUE TITLE
音素バランス文　読み仮名の不備

### ISSUE THREAD

**Issue by uzumushipod** [voice-statistics/voice-statistics.github.com#6]
balance_sentences.txtの57文目
センテンスは「このジェシー役で～」となっていますが、読み仮名が「コノジェシージャニーズーヤクデ～」となっています。

**Comment by ybenjo** [comment]
ご報告いただきありがとうございます．時間が取れ次第修正します．

**Comment by ybenjo** [comment]
@uzumushipod お返事が遅れてしまい申し訳ありませんでした．ご指摘の点修正しました． https://github.com/voice-statistics/voice-statistics.github.com/commit/21e451812110c1bb0065d020b4d3868e0c56321e
