### ISSUE TITLE
043の読みが直感に反している

### ISSUE THREAD

**Issue by Hiroshiba** [voice-statistics/voice-statistics.github.com#7]
https://github.com/voice-statistics/voice-statistics.github.com/blob/bdd4b2bd92db724502c5eb96274d9b1c7d80c3c1/assets/doc/balance_sentences.txt#L44

テキストが

> ハーデースがペルセポネーに恋をしたのはアプロディーテーの策略であるとされている

であるのに対し、読みが

> ハーデースガペルセポネーニコイオシタノハアプロディーテーノサクリャクデアルトサレテイル

となっており、恋をしたの**は**とコイオシタノ**ハ**で読み方が直感的ではありませんでした。

**Comment by ybenjo** [comment]
@Hiroshiba ご指摘ありがとうございます．おっしゃる通り直感的ではありません．時間を見つけ次第修正します (このコーパスだけでなく JVS も含めてコーパスをひたすらに見る・聞く作業，本当に尊敬しています)．

**Comment by skitaoka** [comment]
気になる読みが２つありましたので報告します。

https://github.com/voice-statistics/voice-statistics.github.com/blob/bdd4b2bd92db724502c5eb96274d9b1c7d80c3c1/assets/doc/balance_sentences.txt#L77

* カリュドーンの王女として生を受けた
* カリュドーンノオージョトシテ**ナマ**ヲウケタ

公開されている音声では「セイ」で読まれている。

https://github.com/voice-statistics/voice-statistics.github.com/blob/bdd4b2bd92db724502c5eb96274d9b1c7d80c3c1/assets/doc/balance_sentences.txt#L80

* 中部謙吉の命を受けて
* ナカベケンキチノ**イノチ**ヲウケテ

同様に「メイ」で読まれている。

**Comment by skitaoka** [comment]
もう３点ほど気になる箇所がありました。

https://github.com/voice-statistics/voice-statistics.github.com/blob/master/assets/doc/balance_sentences.txt#L21

* 日本人として受賞
* **ニッポンジン**トシテジュショー

公開されている音声では「ニホンジン」と発音されていました。

https://github.com/voice-statistics/voice-statistics.github.com/blob/master/assets/doc/balance_sentences.txt#L44

* 恋をしたのは
* コイ**オ**シタノハ

「を」も気になりました。

https://github.com/voice-statistics/voice-statistics.github.com/blob/master/assets/doc/balance_sentences.txt#L88

* 福岡ダイエーホークスではなく
* フクオカダイエーホークスデ**ハ**ナク

発音上だと「ワ」でしょうか。

**Comment by ybenjo** [comment]
@Hiroshiba @skitaoka お返事が遅れてしまい申し訳ありませんでした．修正したものを公開しました (https://github.com/voice-statistics/voice-statistics.github.com/commit/21e451812110c1bb0065d020b4d3868e0c56321e )．
